# Official docker image.
variables:
  DOCKER_DRIVER: overlay2

image: docker:latest

before_script:
  - docker login -u $DTR_USERNAME -p $DTR_PASSWORD $DTR_SERVER

stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - docker build --pull -t dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID -t dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest .
    - docker push dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID
    - docker push dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest
    - docker rmi dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID
    - docker rmi dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest

job2:
  stage: deploy
  before_script:
    - apk --update add openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh ubuntu@$DEPLOYMENT_SERVER_IP "docker login -u $DTR_USERNAME -p $DTR_PASSWORD $DTR_SERVER; docker pull dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest; docker service update --with-registry-auth --image dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest hello-node_web"
  # variables:
  #   DOCKER_HOST: "tcp://ucp.clovett.dtcntr.net:443"
